### ISSUE TITLE
timetable for selectedDay()

### ISSUE THREAD

**Issue by sachariase99** [AssHats-G3/Weather_App#12]
Fetch fra openweather (https://openweathermap.org)
Hent selectedDayTimeTable
Brug den lokation som vi får fra FetchLocationData()
Hvis vi ikke kan få selectedDayTimeTable => error()
Brug eventHandler(), som hører på om der klikkes på en dag i fremtiden.
console.log selectedDayTimeTable

**Comment by MarlaRey** [comment]
funktionen hedder: "function getTimeTableForNextDays()" og ikke timetable for selected day, fordi jeg ikke kan lave den for selected day før vi har en viewcode der kan registere user-interaction. jeg laver et nyt issue til det
